### ISSUE TITLE
template-extension 4.0.0 

### ISSUE THREAD

**Issue by tcastelli** [JackAdams/meteor-editable-json#8]
Hi, is it possible to update the packages.json to use the latest version of template-extension?
-> api.use('aldeed:template-extension@3.4.3','client');

**Comment by JackAdams** [comment]
It is. It's just that an update to that package means updating all the packages that depend on it, which is quite the little undertaking.

Is it causing issues? If so, I'll do it sooner rather than later.

**Comment by tcastelli** [comment]
No issues that I know of, just checked template-extension project and it says that 4.0 should be used for meteor 1.2 ( i guess because of refactoring to new es2015) and since this package is depending on 3.4.3 it doesn't allow the whole project to get updated to that version.

No big rush, just on to-do list

**Comment by JackAdams** [comment]
Yeah, this has been on my radar for a while and I did notice that 4.0 was recommended for Meteor 1.2, but, because 3.4.3 seemed to work fine for Meteor 1.0, 1.1 and 1.2, I haven't done the update.  The next time this package gets a bug fix or feature improvement, I'll probably include the update to 4.0.

The thought does occur to me, though, that this might mess with support for apps on Meteor 1.0 or 1.1, which the editable-json package's main user (constellation:console) still aims to support in the medium term.

**Comment by tcastelli** [comment]
Not sure if this would work, but what about allowing both versions in order to not stop people from updating the package?
In this case we could use  api.use('aldeed:template-extension@3.4.3 || 4.0.0');
